# Site settings
title:       Marwen Doukh
email:       marwen@doukh.tn
author:      Marwen Doukh
description: "This is my personal blog. Marwen Doukh"
baseurl:     "blog"
url:         "marwen.doukh.tn"
date_format: "%b %-d, %Y"
header_pages:
 - about.md
 - contact.html


# Optional features
animated:             true
show_related_posts:   true
show_post_footers:    true

# Preview image for social media aka og:image and twitter:image
post_preview_image: true

# Disqus post comments
disqus_shortname:

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
    post_footer:    'Lorem ipsum'
  index:
    coming_soon: 'Coming soon...'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    :title
paginate:     4
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor
